apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy16
  labels:
    app: autodeploy16
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1717444871751
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy16
  template:
    metadata:
      labels:
        app: autodeploy16
    spec:
      containers:
        - name: autodeploy16
          image: acrworkflow1717444871751.azurecr.io/image-workflow-1717444871751:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
