apiVersion: v1
kind: Service
metadata:
  name: autodeploy16
  namespace: namespace-workflow-1717444871751
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: autodeploy16
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000